---
title: "Mehtap Çolak - Join Assignment"
output: html_document
---
```{r warning=FALSE,message=FALSE}
library(dplyr)
library(tidyverse)
load(file = "/Users/mehtapanalyticahouse/Desktop/atp_tennis_data_2017.RData")
```

## Task 1: 

* Rank countries (flag codes) by the singles champions.

```{r}
task1 <- inner_join (tourney_df, player_df, by = c("singles_winner_player_id"="player_id"))
task1 %>%
group_by(flag_code) %>% count(flag_code, sort=TRUE)

```

## Task 2:

* Rank countries which did not get any singles championships by the games. (Won when they win the match)


```{r}

nonchamp_players <-
player_df %>% select(player_id, flag_code) %>% anti_join (.,task1)

nonchamp_players %>% left_join(.,score_df, by=c("player_id"="winner_player_id")) %>% 
  group_by(flag_code) %>% summarise(total_won=sum(winner_games_won, na.rm=TRUE)) %>% arrange(desc(total_won)) 

```

## Task 3:

* Ranking of the names and surnames of the players who won the match in 25 minutes.

```{r}
task3 <- stats_df %>% select(match_id, match_duration)
task3_1 <- inner_join(task3, score_df) %>%
group_by(winner_player_id) %>% filter(match_duration < 25) %>% select(match_duration)

task3_2 <- player_df %>% select(player_id, first_name, last_name) %>% inner_join(.,task3_1, by = c("player_id"="winner_player_id")) %>% arrange(desc(match_duration))


print(task3_2)

```

## Task 4: 

* Number of left and right-handed players among single winner players.

```{r}

task4 <- inner_join(tourney_df, player_df, by = c("singles_winner_player_id"="player_id"))
task4 %>%
group_by(handedness) %>% count(handedness, sort=TRUE)

```
